---
branches:
  only:
    - dev

sudo: required

language: java
jdk: openjdk8

cache:
  directories:
  - $HOME/.m2

before_install:
  - sudo apt-get install -y graphviz libpango1.0-dev libpangocairo-1.0-0 libgirepository1.0-dev
  - sudo pip install pygobject
  - sudo pip install --upgrade https://github.com/kevinpt/syntrax/tarball/master
  - cp .travis.settings.xml $HOME/.m2/settings.xml  
  - echo "optx('SYNTRAX')" > img
  - syntrax -i img -o img.svg
  - cat img.svg

script:
  - mvn javadoc:aggregate -pl :celesta-parent,:celesta-sql,:celesta-core,:celesta-system-services,:celesta-unit
  - mvn generate-resources -pl :celesta-documentation
  - mv target/site/apidocs celesta-documentation/target/generated-docs/apidocs

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: celesta-documentation/target/generated-docs
  on:
    branch: dev
